draft
CRANKBIT/CrankBit-BackEnd pull request #17
Opened 2023-07-07 07:16 UTC by cansibi

2023-07-09 09:18 UTC, Qiming-Liu commented
1. send email utils function, send reset password email.
2. the link in the email should be like `https://<domain>/reset-password?token=<token>`
3. the token should have a `enableChangePassword` property
4. only when the api got `enableChangePassword = true` from the token that pass from client allow the user to change the password

2023-07-14 01:31 UTC, smarthulala commented on src/controllers/auth.ts
> +    <button><a href="/reset-password?token=${token}">${linkText}</a></button>
the url is a relative url, it will not work. use the full url instead

2023-07-14 01:32 UTC, smarthulala commented on src/controllers/auth.ts
> +  tenant.changedPasswords.push({
ternant.password is undefined. I dont think we need the changed password property in the tenant database

2023-07-14 01:33 UTC, smarthulala commented on src/controllers/auth.ts
> +  const { newPassword, token } = req.body
you should add error handling for any functions

2023-07-14 01:38 UTC, smarthulala requested changes

2023-07-14 01:38 UTC, smarthulala commented on src/controllers/auth.ts
> +  res.status(StatusCodes.OK).json({
Is it better to combine two json response into one?

2023-08-15 13:23 UTC, closed without merging