CB16
CRANKBIT/CrankBit-BackEnd pull request #8
Opened 2023-06-20 11:40 UTC by cansibi

2023-06-22 10:16 UTC, Qiming-Liu requested changes

2023-06-22 10:16 UTC, Qiming-Liu commented on src/middleware/createCompanyAccount.ts
> +const connectionString = 'mongodb+srv://AGA:lki09bns37ANZO7U@crank-bit.00j0aqc.mongodb.net/'
we already have these logic in app.ts

2023-06-22 10:16 UTC, Qiming-Liu commented on src/middleware/createCompanyAccount.ts
> +  })
https://codeql.github.com/codeql-query-help/javascript/js-missing-rate-limiting/

2023-06-22 10:19 UTC, Qiming-Liu commented
Mark as draft, because this need refactor, can not merge

2023-06-25 10:21 UTC, LH-Song commented on src/models/User.ts
> +  companyUrls: [
may need id here

2023-06-29 23:33 UTC, LH-Song commented on src/controllers/createCompanyUrl.ts
> +const createCompanyUrl = async (req: Request, res: Response): Promise<void> => {
I believe we already got a company controllers handle this, check main plz

2023-07-02 05:30 UTC, closed without merging